# Generated by Django 3.2.1 on 2024-05-14 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_pdfhistory_image_alter_pdfhistory_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
